<div class="container-lg mt-3">
    <h1>Сайты</h1>
    <div class="table-responsive">
        <table class="table table-bordered table-hover text-nowrap" data-test="urls">
            <thead>
            <tr>
                <th>ID</th>
                <th>Имя</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($urls as $url): ?>
                <tr>
                    <td><?= htmlspecialchars($url->getId()) ?></td>
                    <td>
                        <a href="<?= $router->urlFor('urls.show', ['id' => $url->getId()]) ?>">
                            <?= htmlspecialchars($url->getName()) ?>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
