<div class="container-lg mt-3">
    <?php if (!empty($flash)): ?>
        <div class="flash-messages">
            <?php foreach ($flash as $type => $messages): ?>
                <?php foreach ($messages as $msg): ?>
                    <div class="alert alert-<?= $type ?>">
                        <?= htmlspecialchars($msg) ?>
                    </div>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php if (isset($url)): ?>
        <h1>Сайт: <?= htmlspecialchars($url->getName()) ?></h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                <tr>
                    <td>ID</td>
                    <td><?= htmlspecialchars($url->getId()) ?></td>
                </tr>
                <tr>
                    <td>Имя</td>
                    <td><?= htmlspecialchars($url->getName()) ?></td>
                </tr>
                <tr>
                    <td>Дата создания</td>
                    <td><?= htmlspecialchars($url->getCreatedAt()) ?></td>
                </tr>
                </tbody>
            </table>
        </div>

        <h2 class="mt-5 mb-3">Проверки</h2>
        <form method="post" action="<?= $router->urlFor('urls.checks.store', ['url_id' => $url->getId()]) ?>">
            <input type="submit" class="btn btn-primary" value="Запустить проверку">
        </form>

        <div class="table-responsive mt-3">
            <table class="table table-bordered table-hover" data-test="checks">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Дата создания</th>
                </tr>
                </thead>
                <tbody>
                <?php if (!empty($checks)): ?>
                    <?php foreach ($checks as $check): ?>
                        <tr>
                            <td><?= htmlspecialchars($check->getId()) ?></td>
                            <td><?= htmlspecialchars($check->getCreatedAt()) ?></td>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="6" class="text-center text-muted">
                            Проверки не проводились
                        </td>
                    </tr>
                <?php endif; ?>
                </tbody>
            </table>
        </div>

    <?php else: ?>
        <div class="alert alert-danger">URL не найден</div>
    <?php endif; ?>
</div>
