<div class="container-lg mt-3">
        <div class="row">
            <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                <h1 class="display-3">Анализатор страниц</h1>
                <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
                <form action="<?= $router->urlFor('urls.create') ?>" method="post" class="row">
                    <div class="col-8">
                        <label for="text" class="visually-hidden">Url для проверки</label>
                        <input
                                type="text"
                                name="url[name]"
                                value="<?= htmlspecialchars($old['url']['name'] ?? '') ?>"
                                class="form-control form-control-lg <?= !empty($errors) ? 'is-invalid' : '' ?>"
                                placeholder="https://www.example.com"
                        >
                        <?php if (!empty($errors)): ?>
                            <div class="invalid-feedback" role="alert">
                                <ul class="mb-0">
                                    <?php foreach ($errors['url.name'] as $error): ?>
                                        <li><?= htmlspecialchars($error) ?></li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        <?php endif ?>
                    </div>
                    <div class="col-2">
                        <input type="submit" class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3"
                               value="Проверить">
                    </div>
                </form>
            </div>
        </div>
    </div>
